
service: whiskey-notification
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

package:
  patterns:
    - '!__mocks__/**'
    - '!__tests__/**'
    - '!node_modules/aws-sdk/**'
    - '!aws/**'
    - '!data/**'
    - 'src/**'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - "sns:Publish"
          Resource: "*"

plugins:
  - serverless-step-functions
functions:
  get-users:
    handler: src/lambda/getUsers.handler
  alert-user:
    handler: src/lambda/alertUser.handler
  get-products:
    handler: src/lambda/getProducts.handler
  store-product:
    handler: src/lambda/storeProduct.handler

stepFunctions:
  stateMachines:
    whiskeyCheck:
      name: whiskey-notification-check
      events:
        - schedule: cron(30 15 * * ? *)
          name: 'whiskey-notification-execution'
          input:
            bucket: "whiskey-notify-data"
            send: true
      definition:
        StartAt: GetProducts
        States:
          GetProducts:
            Type: Task
            Resource:
              Fn::GetAtt: [get-products,Arn]
            Next: GetNextProduct
          GetNextProduct:
            Type: Choice
            Choices:
              - Variable: "$.next"
                StringEquals: "SENTINEL"
                Next: GetUsers
            Default: StoreProductInfo
          StoreProductInfo:
            Type: Task
            Resource:
              Fn::GetAtt: [store-product,Arn]
            Next: GetNextProduct
          GetUsers:
            Type: Task
            Resource:
              Fn::GetAtt: [get-users,Arn]
            Next: GetNextUser
          GetNextUser:
            Type: Choice
            Choices:
              - Variable: "$.next"
                StringEquals: "SENTINEL"
                Next: DoneUsers
            Default: NotifyUser
          NotifyUser:
            Type: Task
            Resource:
              Fn::GetAtt: [alert-user,Arn]
            Next: GetNextUser
          DoneUsers:
            Type: Succeed