
service: whiskey-notification
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

package:
  patterns:
    - '!__mocks__/**'
    - '!__tests__/**'
    - '!node_modules/aws-sdk/**'
    - '!aws/**'
    - '!data/**'
    - 'src/**'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:*"
          Resource: "*"
        - Effect: Allow
          Action:
            - "sns:Publish"
          Resource: "*"

plugins:
  - serverless-step-functions
functions:
  read-list:
    handler: src/lambda/getFileList.handler
  alert-user:
    handler: src/lambda/alertUser.handler
  store-product:
    handler: src/lambda/storeProduct.handler

stepFunctions:
  stateMachines:
    whiskeyCheck:
      name: whiskey-notification-check
      events:
        - schedule: cron(30 15 * * ? *)
          name: 'whiskey-notification-execution'
          input:
            bucket: "whiskey-notify-data"
            send: true
      definition:
        StartAt: LoadProducts
        States:
          LoadProducts:
            Type: Pass
            Result: "products.json"
            ResultPath: "$.inputFile"
            Next: GetProducts
          GetProducts:
            Type: Task
            Resource:
              Fn::GetAtt: [read-list,Arn]
            Next: GetNextProduct
          GetNextProduct:
            Type: Choice
            Choices:
              - Variable: "$.next"
                StringEquals: "SENTINEL"
                Next: LoadUsers
            Default: StoreProductInfo
          StoreProductInfo:
            Type: Task
            Resource:
              Fn::GetAtt: [store-product,Arn]
            Next: GetNextProduct
          LoadUsers:
            Type: Pass
            Result: "users.json"
            ResultPath: "$.inputFile"
            Next: GetUsers
          GetUsers:
            Type: Task
            Resource:
              Fn::GetAtt: [read-list,Arn]
            Next: GetNextUser
          GetNextUser:
            Type: Choice
            Choices:
              - Variable: "$.next"
                StringEquals: "SENTINEL"
                Next: DoneUsers
            Default: NotifyUser
          NotifyUser:
            Type: Task
            Resource:
              Fn::GetAtt: [alert-user,Arn]
            Next: GetNextUser
          DoneUsers:
            Type: Succeed